export const RESET_STATE = 'RESET_STATE';

export const SAVE_TOKEN = 'SAVE_TOKEN';
export const REMOVE_TOKEN = 'REMOVE_TOKEN';

export const SET_ORDER_HISTORY = 'SET_ORDER_HISTORY';
export const ADD_ORDER_TO_HISTORY = 'ADD_ORDER_TO_HISTORY';

export const SET_PREVIEW_DATA = 'SET_PREVIEW_DATA';
export const FETCHING_PREVIEW = 'FETCHING_PREVIEW';
export const ERROR_FETCHING_PREVIEW = 'ERROR_FETCHING_PREVIEW';
export const SET_CANCELING_STATUS = 'SET_CANCELING_STATUS';

export const SET_MENU_DATA = 'SET_MENU_DATA';
export const UPDATE_MENU_ITEM = 'UPDATE_MENU_ITEM';
export const DELETE_MENU_ITEM = 'DELETE_MENU_ITEM';

export const SET_NEW_ORDER_MEAL = 'SET_NEW_ORDER_MEAL';
export const UPDATE_NEW_ORDER_MEAL = 'UPDATE_NEW_ORDER_MEAL';
export const REMOVE_NEW_ORDER_MEAL = 'REMOVE_NEW_ORDER_MEAL';
export const RESET_NEW_ORDER_STATE = 'RESET_NEW_ORDER_STATE';
